// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ✅ Configuración iOS - Valores de GoogleService-Info.plist
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB56rWRNjX2OfMg9P6OFtAaynBazX8N3tc',
    appId: '1:580564332826:ios:d9eabfd8ad6a798571fca3',
    messagingSenderId: '580564332826',
    projectId: 'apartalo-10146',
    storageBucket: 'apartalo-10146.firebasestorage.app',
    iosBundleId: 'com.rosal.apartaloApp',
  );

  // Android - Configurar cuando agregues google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB56rWRNjX2OfMg9P6OFtAaynBazX8N3tc',
    appId: '1:580564332826:android:PLACEHOLDER',
    messagingSenderId: '580564332826',
    projectId: 'apartalo-10146',
    storageBucket: 'apartalo-10146.firebasestorage.app',
  );
}
